### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by RubenKelevra** [luben/bird-multigraph-plugin#2]
[root@bragi muninplugins]# munin-run bird
given is experimental at /etc/munin/plugins/bird line 66.
when is experimental at /etc/munin/plugins/bird line 67.
Smartmatch is experimental at /etc/munin/plugins/bird line 69.
when is experimental at /etc/munin/plugins/bird line 72.
when is experimental at /etc/munin/plugins/bird line 76.
when is experimental at /etc/munin/plugins/bird line 79.
when is experimental at /etc/munin/plugins/bird line 82.
Smartmatch is experimental at /etc/munin/plugins/bird line 83.
when is experimental at /etc/munin/plugins/bird line 86.
Smartmatch is experimental at /etc/munin/plugins/bird line 87.
when is experimental at /etc/munin/plugins/bird line 93.
Smartmatch is experimental at /etc/munin/plugins/bird line 94.
when is experimental at /etc/munin/plugins/bird line 101.
given is experimental at /etc/munin/plugins/bird line 227.
when is experimental at /etc/munin/plugins/bird line 228.
when is experimental at /etc/munin/plugins/bird line 229.
Modification of a read-only value attempted at /etc/munin/plugins/bird line 65.

**Comment by luben** [comment]
Hi, I just commited a fix for the warnings.

**Comment by luben** [comment]
> Modification of a read-only value attempted at /etc/munin/plugins/bird line 65.

this does bot happen for me. which version of perl do you use?

**Comment by RubenKelevra** [comment]
Latest stable I think, it's an arch linux:

[ruben@i3 ~]$ perl -v

This is perl 5, version 20, subversion 2 (v5.20.2) built for x86_64-linux-thread-multi

**Comment by luben** [comment]
Could you try the last commit. Does it solve the problem for you?

**Comment by RubenKelevra** [comment]
You mean the "7 days ago Use common sense"?

No, it doesnt:

[root@bragi ~]# munin-run bird
Modification of a read-only value attempted at /etc/munin/plugins/bird line 63.

**Comment by luben** [comment]
Hi, sorry for the delay. Pushed a small change that should fix it.
